kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: wp-hpa

spec:

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wp-deployment

  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 # this is calculated form the requested